# Generated by Django 2.1.5 on 2019-01-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default='', null=True)),
                ('symbol', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('open1', models.DecimalField(blank=True, decimal_places=6, default='', max_digits=10, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=6, default='', max_digits=10, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=6, default='', max_digits=10, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=6, default='', max_digits=10, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=6, default='', max_digits=10, null=True)),
            ],
            options={
                'db_table': 'stocks_table',
                'managed': False,
            },
        ),
    ]
